[tool.poetry]
name = "reflex-chakra"
version = "0.1.0a1"
description = "reflex using chakra components"
authors = [
    "Elijah Ahianyo <elijah@reflex.dev>"
]
readme = "README.md"
packages = [{include = "reflex_chakra"}]

[tool.poetry.dependencies]
python = "^3.8"
reflex = ">=0.5.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
target-version = "py38"
lint.select = ["B", "D", "E", "F", "I", "SIM", "W"]
lint.ignore = ["B008", "D203", "D205", "D213", "D401", "D406", "D407", "E501", "F403", "F405", "F541"]
lint.pydocstyle.convention = "google"

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
"tests/*.py" = ["D100", "D103", "D104", "B018"]
"*.pyi" = ["D301", "D415", "D417", "D418", "E742"]